print("Mad Libs Game!!\n")
print("Lets Play")
person = input("Enter a person: ")
adj1 = input("Enter an adjective: ")
adj2 = input("Enter another adjective: ")
noun = input("Enter in a noun: ")
adj3 = input ("Enter in an adjective: ")
noun2 = input("Enter in a noun: ")
adj4 = input("Enter in another adjective: ")
adj5 = input ("Enter in an adjective: ")
verb = input("Enter in a verb: ")
verb2 = input("Enter in another verb: ")
verb3 = input("Enter a different verb: ")
adj5 = input("Enter in a final adjective: ")
verb4 = input("Enter your final verb: ")

print( " ")

print("Yesterday, " +person + " and I went to the park.")
print("On our way to the "+ adj1 + " park, we saw a " +adj2 +" " +noun+ " on a bike.")
print("We also saw big "+ adj3 + " balloons tied to a "+ noun2+".")
print("Once we got to the "+ adj4 + " park, the sky turned "+adj5 +".")
print("It started to "+ verb+ " and " + verb2+".")
print(person+ " and I "+verb3+ " all the way home.")
print("Tomorrow we will try to go to the "+ adj5 + " park again and hope it doesn't " + verb4+"." )
